---
- name: Creates /opt directory
  file:
    path: /opt
    state: directory

- name: install Mutt package
  package:
    pkg: mutt
    state: present

- name: Download and extract Lynis
  unarchive:
    src: "{{ lynis_download_url }}"
    dest: "{{lynis_home_dir}}"
    copy: no

- name: upload cron run script
  template:
    src: lynis.j2
    dest: /etc/cron.daily/lynis
    mode: 0755

- name: create custom Lynis configuration
  copy:
    src: custom.prf
    dest: "{{lynis_home_dir}}/lynis/custom.prf"
    owner: root
    group: root
    mode: 0644
