---
- name: install package
  package:
    pkg: rkhunter
    state: present

- name: configure init
  template:
    src: rkhunter.j2
    dest: /etc/default/rkhunter
    owner: root
    group: root
    mode: 0644

- name: upload rkhunter local config
  template:
    src: rkhunter.conf.local.j2
    dest: /etc/rkhunter.conf.local
    owner: root
    group: root
    mode: 0644
