---
- name: add nodesource key
  apt_key: url="{{ item }}"
  with_items:
    - "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    - "https://dl.yarnpkg.com/debian/pubkey.gpg"

- name: add nodesource repository
  apt_repository: repo="{{ item }}"
    state=present
  with_items:
    - "deb https://deb.nodesource.com/node_14.x {{ansible_distribution_release}} main"
    - "deb-src https://deb.nodesource.com/node_14.x {{ansible_distribution_release}} main"
    - "deb https://dl.yarnpkg.com/debian/ stable main"

- name: install package
  package:
    pkg:
      - build-essential
      - libpng-dev
      - letsencrypt
      - nodejs
      - yarn
    state: latest
