---
galaxy_info:
  author: Néstor Salceda
  description: RKHunter installation and configuration
  license: Apache-2.0
  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - buster
  galaxy_tags:
    - system
