---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Debian10
    image: geerlingguy/docker-debian10-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/sbin/init"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      Debian10:
        rkhunter_report_email: "sysadmin@email.org"
        rkhunter_config_local:
          allowhiddendir:
            - /tmp
          allowhiddenfile:
            - /tmp/file1
          allowdevfile:
            - /dev/sdb1
          scriptwhitelist:
            - /root/some_script
          pwdless_accounts:
            - myself
          otherrules:
            - SCANROOTKITMODE=THOROUGH
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint .
